import type { Metadata } from "next";
import { dir } from 'i18next'
import { Inter } from "next/font/google";
import "../globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React",
  description: "Generated by create next app",
};

const languages = ['en', 'nl'];

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}


export default function RootLayout({
  children,
  params: {
    lng
  }
}: {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className="secondary-bg">
        <main className="container">
          <h1 className="underlined">Tasky</h1>
          {children}
        </main>
      </body>
    </html>
  );
}
