import type { Metadata } from 'next';
import { Roboto } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import Image from "next/image";
import Logo from "../../common/public/logo.svg";
import Navigation from "./_components/Navigation";

import './globals.scss';

const roboto = Roboto({ subsets: ["latin"], weight: ["300","400", "700", "900"], display: "swap", preload: true, style: "normal" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={`${roboto.className} secondary-bg`}>
          <main>
            <header>
              <Image
                src={Logo}
                alt="Application Logo"
                className="logo"
                width={100}
                height={24}
                priority
              />
              <Navigation />
            </header>
            <div className="container">{children}</div>
          </main>
        </body>
      </html>
    </UserProvider>
  );
}
